name: daily-sync-to-gitea

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to Gitea
        run: git push --mirror "$GITEA_PUSH_URL"
        env:
          GITEA_PUSH_URL: ${{ secrets.GITEA_PUSH_URL }}
